Pipfile, Pipfile.lock
Added Pipfile and Pipfile.lock to work with Pipenv
=> 📝 Added Pipfile

pyscord/_config.py
- `adds`: ...
- `fixed`: probably copy paste error in `_config.py`
- `improvements`: ...
=> Fix copy-paste error in _config.py

docs/CONTRIBUTING.md, goals/command.md
- `adds`: ...
- `fixed`: fixed typos in `docs/CONTRIBUTING.md` and `goals/command.md`
- `improvements`: ...
=> Fixed typos

.readthedocs.yml, Pipfile, setup.py
-   `fixed`: Changed Python version to 3.7 to avoid issues with package support
see #16 
=> ⬆️ Update Python version to 3.7

pincer/client.py, pincer/core/http.py
-   `fixed`: fixed errors in `HTTPClient` class
-   `improvements`: refactored `HTTPClient` class, it now creates only one session and keeps it
=> ♻️ refactored HTTPClient

pincer/client.py, pincer/core/http.py
-   `fixed`: errors from previous PR
=> Fix errors from previous PR

docs/AUTHORS.md, docs/CODE_OF_CONDUCT.md, docs/CONTRIBUTING.md, docs/PYPI.md, docs/README.md
-   `adds`: syncs PyPI.md and README.md 
-   `fixed`: markdown issues (trailing spaces, extra lines and spaces, indentation) 
-   `improvements`: markdown best practices
=> 🎨 improve md files

pincer/objects/member.py
-   `adds`: Guild Member Class
-   [ ] My Code follows the pep8 code style.
=> 🧍 Added Guild Member Class

pincer/objects/application.py, pincer/objects/channel.py, pincer/objects/emoji.py, pincer/objects/guild.py, pincer/objects/invite.py, pincer/objects/member.py, pincer/objects/role.py, pincer/objects/sticker.py
-   `adds`: Application Class, Invite Class, Role Class, Sticker Class
-   `fixed`: Added the new Class Types to Guild, Channel, Emoji and Member
-   [] I have tested my changes with the current requirements
=> 👽 Added More Classes

docs/PYPI.md, docs/README.md
-   `fixed`: a handful of typos in `README.md` and `PYPI.md`
-   `improvements`: the order of installation troubleshooting solutions
=> ✏️ Fixed typos

pincer/objects/embed.py
-   `improvements`: Refactored Embed.py
Added type hints
Allowed for EmbedFieldError to be constructed with a string like other Exceptions.
=> Refactored Embed.py

pincer/objects/sticker.py, pincer/objects/webhook.py, pincer/objects/welcome_screen.py
-   `adds`: Welcome Screen & Welcome Screen Channel, Sticker Pack & Sticker Item, Webhook Objects
=> Welcome Screen, Sticker and Webhook Objects

pincer/objects/audit_log.py, pincer/objects/sticker.py, pincer/objects/welcome_screen.py, pincer/utils/snowflake.py
-   `adds`: Added a missing `typing.List` import in `pincer/objects/sticker.py`
-   `improvements`: Removed an unused `typing.List` import found in `pincer/objects/welcome_screen.py`
=> 🐛 Fixed imports

.readthedocs.yml, Pipfile, setup.py
-   `fixed`: Python version changed to 3.8
=> ⬆️ Python version changed to 3.8

pincer/objects/ban.py
=> ✨ Added Ban object

pincer/objects/application_command.py, pincer/objects/attachment.py, pincer/objects/audit_log.py, pincer/objects/ban.py, pincer/objects/button.py, pincer/objects/followed_channel.py, pincer/objects/guild_widget.py, pincer/objects/integration.py, pincer/objects/interactions.py, pincer/objects/message_component.py, pincer/objects/message_reference.py, pincer/objects/overwrite.py, pincer/objects/reaction.py, pincer/objects/select_menu.py, pincer/objects/voice_region.py, pincer/utils/snowflake.py
**application_command.py:**
- ApplicationCommandInteractionDataOption object,
- ApplicationCommandOptionChoice object,
- ApplicationCommandOption object,
- ApplicationCommand object
**attachment.py:**
- Attachment object
**button.py:**
- Button object
**followed_channel.py:**
- FollowedChannel object
**guild_widget.py:**
- GuildWidget object
**integration.py:**
- IntegrationAccount object,
- IntegrationApplication object,
- Integration object
**interactions.py:**
- ResolvedData object,
- InteractionData object,
- MessageInteraction object,
- Interaction object
**message_component.py:**
- MessageComponent object
**message_reference.py:**
- MessageReference object
**overwrite.py:**
- Overwrite object
**reaction.py:**
- Reaction object
**select_menu.py:**
- SelectOption object,
- SelectMenu …
=> 💥 Added 22 objects + documentation for 3 files

pincer/objects/embed.py, pincer/utils/api_object.py, pincer/utils/constants.py
-   `adds`: After 20 years i finally added chaining
-   `improvements`: MISSING is now a class so it can be used with typing for easily. APIObject as_dict method has been changed to ignore values set to missing instead of None.
-   [ x] I have tested my changes with the current requirements
-   [ x] My Code follows the pep8 code style.
=> Embed object chaining

.readthedocs.yml, docs/conf.py, pincer/client.py, pincer/core/gateway.py, pincer/core/heartbeat.py, pincer/core/http.py, pincer/exceptions.py, pincer/objects/user.py, pincer/utils/extraction.py, pincer/utils/insertion.py, pincer/utils/types.py
-   `improvements`: Changed, added and edited many docstrings
See https://pincer-test.readthedocs.io/en/improve-docs for preview.
=> Improved docs

pincer/objects/application_command.py, pincer/utils/timestamp.py
-   `adds`: `Timestamp` datatype
=> ✨ Added Timestamp datatype

pincer/objects/application.py, pincer/objects/channel.py, pincer/objects/guild.py, pincer/objects/invite.py, pincer/objects/member.py, pincer/objects/role.py, pincer/objects/sticker.py, pincer/objects/user.py, pincer/objects/webhook.py, pincer/objects/welcome_screen.py
-   `adds`: Added missing import in `guild.py`
-   `fixed`: Corrected data types (`int`→`Snowflake`; `str`→`Timestamp`) in `application.py`, `channel.py`, `guild.py`, `invite.py`, `member.py`, `role.py`, `sticker.py`, `user.py`, `webhook.py` and `welcome_screen.py`
-   `improvements`: Removed unused import in `role.py`
=> 🎨 Fixed imports

pincer/objects/guild_template.py, pincer/objects/invite.py, pincer/objects/voice_state.py
-   `adds`: `VoiceState` object, `InviteMetadata` object, `GuildTemplate` object
=> ✨ Added 3 new objects

pincer/objects/channel.py, pincer/objects/guild.py, pincer/objects/stage.py, pincer/objects/thread.py
-   `adds`: ThreadMetadata, ThreadMember and StageInstance
=> ✨ Added Thread and Stage objects

pincer/objects/channel.py
=> ✨ Added ChannelMention datatype

pincer/objects/message.py
=> ✨ Added Message object

pincer/objects/guild.py
-   `improvements`: Unavailable Guild would throw a TypeError since they didn't have enough arguments. Now they throw a UnavailableGuildError.
-   [x ] I have tested my changes with the current requirements
-   [x ] My Code follows the pep8 code style.
=> Unavailable Guild throw UnavailableGuildError()

.readthedocs.yml, docs/PYPI.md, docs/README.md, docs/api.rst, docs/index.rst, docs/installing.rst, docs/quickstart.rst, docs/tutorial/index.rst
[See preview build here](https://pincer-test.readthedocs.io/en/docs-update/)
-   `adds`: More information to the documentation
-   `fixed`: The formatting with how the docs were laid out.
-   `improvements`: Everything is better
=> Docs update

pincer/exceptions.py, pincer/objects/application.py, pincer/objects/channel.py, pincer/objects/emoji.py, pincer/objects/guild.py, pincer/objects/invite.py, pincer/objects/member.py, pincer/objects/role.py, pincer/objects/sticker.py, pincer/objects/user.py, pincer/objects/webhook.py, pincer/objects/welcome_screen.py
-   `adds`: A lot of documentation for the discord objects
-   `fixed`: Member object renamed to GuildMember
-   [x ] I have tested my changes with the current requirements
-   [x ] My Code follows the pep8 code style.
=> Added more documentation

pincer/objects/__init__.py
-   `adds`: Added missing objects in `objects/__init__.py`
=> 🎨 Added missing objects

pincer/utils/constants.py
=> 🐛 Bug with APINullable

pincer/client.py, pincer/commands.py
-   `improvements`: Replaced `dict()` and `list()` function calls with `{}` and `[]`
=> ⚡️ Replaced function calls with bracket notation

pincer/client.py, pincer/commands.py, pincer/core/gateway.py, pincer/core/http.py, pincer/objects/application_command.py, pincer/objects/channel.py, pincer/objects/user.py, pincer/utils/api_object.py, setup.py
-   `fixed`: few type issues and unescaped backslashes in docstrings
=> Fixed few type issues and backslashes

pincer/client.py
-   `improvements`:
Fixes an error's grammatical syntax.
=> Improve event naming error message.

docs/PYPI.md, docs/README.md, docs/pincer.objects.rst, pincer/commands.py, pincer/objects/__init__.py, pincer/objects/app_command.py, pincer/objects/application.py, pincer/objects/audit_log.py, pincer/objects/ban.py, pincer/objects/button.py, pincer/objects/channel.py, pincer/objects/emoji.py, pincer/objects/guild.py, pincer/objects/guild_member.py, pincer/objects/guild_template.py, pincer/objects/integration.py, pincer/objects/intents.py, pincer/objects/interactions.py, pincer/objects/invite.py, pincer/objects/message.py, pincer/objects/message_component.py, pincer/objects/reaction.py, pincer/objects/select_menu.py, pincer/objects/stage.py, pincer/objects/sticker.py, pincer/objects/user.py, pincer/objects/voice_state.py, pincer/objects/webhook.py
-   `adds`:
- `Connection` object,
- `discoverable_disabled` property for `StageInstance`
-   `improvements`:
- Renamed `application_command.py` to `app_command.py`
- Changed `Enum`s to `IntEnum`s
- Updated local imports
=> ✨ Added a Connection object

docs/pincer.objects.rst, pincer/objects/guild.py, pincer/objects/guild_features.py
-   `adds`: Guild Features enum
=> Guild Features

pincer/client.py, pincer/commands.py, pincer/core/gateway.py
-   `improvements`: Use only one instance of HttpClient for all requests
=> ♻️ Use one instance of HttpClient for all requests

pincer/middleware/message_delete.py
-   `fixed`: Imports in `message_delete.py`
=> 🐛 Added missing imports

pincer/client.py, pincer/middleware/__init__.py, pincer/objects/channel.py, pincer/objects/guild.py
-   `adds`: 
- `Client.get_guild(id)` to get a guild object
- `Guild.from_id`
- `ChannelType.from_id`
- Extra Channel Types (Adding functionality is a TODO)
- `_channel_type_map` to use the correct class
- `Guild.nsfw` (missing from discord docs but in the v9 api)
Code has been tested with a bot.
=> ✨Guild Object with Client.get_guild

pincer/objects/interaction_base.py
=> 🐛 Added member to MessageInteraction

pincer/middleware/interaction_create.py
-   `fixed`: Issue with imports
=> 🐛 Import bug

pincer/client.py, pincer/middleware/error.py, pincer/middleware/interaction_create.py, pincer/middleware/message_create.py, pincer/middleware/message_delete.py, pincer/middleware/ready.py, pincer/objects/channel.py, pincer/objects/guild.py, pincer/objects/guild_member.py, pincer/objects/interactions.py, pincer/objects/user.py, pincer/objects/user_message.py, pincer/utils/api_object.py, pincer/utils/conversion.py
-   `adds`: These methods
- `Client.get_user`
- `Guild.get_member`
- `Guild.modify_member`
- `User.from_id`
> Note: This will not work without #72 being merged
=> Methods to Guild and User

Pipfile, pincer/client.py, pincer/core/gateway.py, pincer/middleware/payload.py
-   `adds`: A `payload` event, which forwards any gateway messages.
Recreated #74 because of a GitHub :bug:.
=> Add payload event

pincer/middleware/error.py, pincer/middleware/interaction_create.py, pincer/middleware/message_create.py, pincer/middleware/message_delete.py, pincer/objects/guild.py, pincer/objects/guild_member.py, pincer/utils/conversion.py
=> 🚑️ Fixed dict merging in Python 3.8.8

Pipfile
-   `fixed`: Pipfile has all files in requirements, dependencies are pinned to specific versions
=> 📌 Update Pipfile

.github/workflows/codecov.yml, requirements_dev.txt
-   `adds`: A CI ton have better insight on coverage
=> :construction_worker: Adding Codecov

pincer/objects/guild/channel.py
-   `adds`: `Channel.edit`
-   `fixed`: `Channel.from_id` works
Implementation of #93  
=> ✨ Added `Channel.edit`

examples/basic_cogs/cogs/on_ready.py, examples/basic_cogs/cogs/say.py, examples/basic_cogs/run.py, pincer/__init__.py, pincer/middleware/activity_join.py
=> 🔖 `0.9.0` fix

docs/CONTRIBUTING.md
-   `adds`: Adds note in CONTRIBUTING.md to use numpydocs style for docstrings
=> :memo: Add note to use numpydocs style for docstrings in CONTRIBUTING.md

docs/PYPI.md, docs/README.md, pincer/client.py, pincer/core/gateway.py, pincer/core/heartbeat.py, pincer/exceptions.py, pincer/middleware/interaction_create.py, pincer/objects/app/command.py, pincer/objects/app/interactions.py, pincer/objects/guild/member.py, pincer/objects/message/context.py, pincer/utils/convert_message.py, pincer/utils/insertion.py, pincer/utils/timestamp.py
Bugfix in command loader, dispatcher close & partialmember + removed some __post_init__s.
Added:
* MessageContext interaction property
* MessageContext.send coroutine
* Interaction.ack coroutine
* Restart method
closes #166 
closes #161
=> ✨ 🐛  new interaction features, bugfix and refactor

pincer/objects/app/interactions.py, pincer/objects/message/message.py
-   `fixed`: Images work again
Note: Didn't do docs since it'll be the old style. Ill add them in when I merge main with PR 155.
=> 🐛 Pillow images can be sent in an interaction

requirements.txt
-   `adds`: Better requirement Versioning
=> Added support for newer aiohttp versions

pincer/objects/guild/channel.py, pincer/objects/guild/guild.py, pincer/objects/user/user.py
-   `adds`: Added docs for `Channel.fetch_message`, `Guild.kick`, `Guild.ban`, `User.get_avatar`
-   `improvements`: Added missing parameter for `Channel.edit`, auto-formatted `objects.user.user.py`
=> 📝 Added docs

.github/workflows/setup_generator.yml, .github/workflows/sort_alls.yaml
-   `fixed`: Workflow commits were using unicode emojis instead of colon/markdown emojis
=> :hammer: Fix workflow commits using unicode emojis

pincer/client.py, pincer/commands.py, pincer/middleware/ready.py
Reverts [7e40a04](https://github.com/Pincer-org/Pincer/commit/7e40a04b28368142067c434d14bf6ae1bab6a9a1) - Caused a bug where you couldn't remove commands
Reverts [16f1413](https://github.com/Pincer-org/Pincer/commit/16f1413342b88db51b6a4f48877889d9bd157075) - Caused a bug where commands wouldn't be deleted if your bot didn't have any commands.
=> :ambulance: revert 16f1413 and 7e40a04

.gitignore
Makes configs for Visual Studio 2022, 2019, 2017 etc ignored
=> :technologist: Adding Visual Studio Configs To gitignore

pincer/objects/guild/guild.py
Closes #303
If I was meant to do it the other way and remove the top import please tell me
=> :bug: Fix Python 3.10

.gitignore, docs/conf.py, docs/requirements.txt
-   `adds`: Mermaid. It looks really ugly and honestly I have no idea how to make it look good on dark mode.
=> :memo: added mermaid support to docs

pincer/objects/guild/channel.py
-   `adds`: `Channel.bulk_delete_messages()` and `Channel.edit_permissions()`
-   `improvements`: Changed some indentation of function parameters and made `Channel.delete()` use `remove_none()`.
=> :sparkles: Added `Channel.bulk_delete_messages()` and `Channel.edit_permissions()`

pincer/objects/guild/guild.py, pincer/objects/guild/member.py, setup.cfg
-   `adds`: Attribute to ``GuildMember`` and param to ``Guild.modify_member``
I have no idea how pincer works really
=> :sparkles: Add timeouts.

pincer/objects/message/message.py
-   `fixed`: Allows clearing fields when editing a message 
-   [ ] My Code follows the pep8 code style.
=> :bug: filter out message fields if None instead of False

requirements.txt
Already has been tested. Works fine.
=> :arrow_up: update aiohttp to ~=3.8

pincer/objects/message/sticker.py
refer to [##369](https://github.com/Pincer-org/Pincer/issues/369)
=> :bug: Fix sticker description

pincer/objects/guild/guild.py, pincer/objects/guild/invite.py
-   `adds`: Get Invite & Delete invite
=> :sparkles: Get Invite & Delete invite

pincer/objects/guild/channel.py
You copy pasted too fast
-   `improvements`: docs i guess
=> :pencil: Fixed typo in VoiceChannel and NewsChannel

pincer/objects/guild/guild.py
-   `fixed`: api endpoint for `add_guild_member_role` and `remove_guild_member_role`
=> :bug: Fixed api endpoint for guild member role actions

pincer/objects/guild/guild.py
-   `adds`: The ability to pass ``GuildMember`` to ``Guild.kick`` and ``Guild.ban``
=> feat: Allow for GuildMember in kick & ban

pincer/objects/guild/channel.py
=> :memo: Docs improvements

pincer/client.py, pincer/objects/guild/guild.py, pincer/objects/message/user_message.py
-   `adds`: Method for [Crosspost Message](https://discord.com/developers/docs/resources/channel#crosspost-message) to `Client` and `UserMessage`
=> :sparkles: Crosspost Method

pincer/objects/guild/guild.py
this is for fixing bugs like guild.get_invites() not working
-   `improvements`: imports
=> ♻️ reorganised imports

pincer/objects/guild/guild.py
-   `adds`: [not a code change] document `with_counts` in `Guild.from_id`
-   `fixed`: fixes #419
=> :memo: document with_counts in Guild.from_id

docs/README.md
Well that's a silly PR but it needs to be done I guess :woman_shrugging: 
-   `fixed`: copyright year in `README.md`
=> chore: update copyright year in README
