Pincer-org/Pincer

pincer/client.py

-   `improvements`: Removed `global` calls, since the referenced variable was a global variable & a mutable object, hence the `global` keyword had no effect on it.

🔥 Removed the global keyword

---

pincer/objects/integration.py
pincer/objects/interactions.py
pincer/objects/message.py
pincer/objects/role.py
pincer/utils/timestamp.py

-   `adds`:
- support for type `datetime` in `Timestamp.parse`
- added missing Message types in `interactions.py`
- added missing RoleTags type in `role.py`
-   `fixed`: 
-   `improvements`:
- Removed unused `datetime` import from `integration.py`
- Changed `str` to `Timestamp` for `Integration.synced_at`
- Removed `Integration.set_synced_at` function
- Refactored the version check in `message.py:MessageType`

🎨 Fixed imports & types

---

pincer/commands.py
pincer/core/http.py
pincer/middleware/interaction_create.py

-   `adds`: 
- Ability to have commands with `yield` (sends a webhook to respond). [see API docs for implementation](https://discord.com/developers/docs/interactions/receiving-and-responding#followup-messages)
- When creating the command, it checks if it is coroutine or asyncgenerator
- API Exception includes a JSON property to see the response when using try-except. (this is taken advantage of in this pr)
- A separate function to convert a message to a `Message` object

Yieldable commands

---

pincer/client.py
pincer/commands.py

Implements #84 and #91.
```py
@command()
async def foo(bar: (str, "A sample command!")):
...
```
First tuple argument: type
Second tuple argument: description
Description defaults to `Description not set`

Improved the way events are executed + implemented command argument descriptions.

---

docs/PYPI.md
docs/README.md
pincer/__init__.py
pincer/commands.py
pincer/objects/app_command.py
pincer/utils/__init__.py
pincer/utils/types.py

Implements command argument choices.
You can add choices to arguments through the `pincer.Choices` *(which is an alias for `typing.Literal`)*.
Choice values must consist of the same type, and there can only be a maximum of 25 choices.
```py
@command()
async def choose(self, choice: Choices["Test", "Sample lol", "Geheh"]):
return f"You chose: `{choice}`"
```
You can manually override the default name (which is set to the value) of a choice.
This is done through a tuple, where the first value is the choice name and the second one is the value. These can be combined with default choices. *(so no tuple, as seen in the example)*
```py
@command()
async def choose(
self,
choice: Choices[
("This will be the test value", "Test"),
"Sample lol",
"Geheh"
]
):
return f"You chose: `{choice}`"
```
*(So …

Implements command choices

---

.flake8

-   `fixed`: Ignore W503 warning in flake8 so that we aren't warning for line breaks both before and after binary operators, just after.

Ignore line break before binary operator in flake8

---

examples/guessing_game.py
pincer/commands.py

```py
@command  # () is optional
async def test():
return Message("Succes")
```
This simply allows for a non-parenthesised `@command` decorator

:children_crossing: Allow non-parenthesised `@command` decorator

---

pincer/objects/guild/guild.py

`adds`: 
- `Guild.get_roles`,
- `Guild.create_role`,
- `Guild.edit_role_position`,
- `Guild.edit_role`,
- `Guild.delete_role`,
- `Guild.get_bans`,
- `Guild.get_ban`,
- `Guild.unban`

:sparkles: Added role and ban related Guild methods

---

pincer/client.py
pincer/objects/guild/guild.py

- `Client.get_guild_template`
- `Guild.get_templates`
- `Guild.create_template`
- `Guild.sync_template`
- `Guild.edit_template`
- `Guild.delete_template`

:sparkles: Added `GuildTemplate` related endpoints

---

pincer/core/http.py

-   `adds`: User-Agent header. Read the docs and realized I missed this lol. Would've stopped us from being added to the discord libs in the docs if we didn't have it.
Im open to suggestions on how to make this not suck :pensive: 

:passport_control: added User-Agent header

---

pincer/objects/guild/guild.py
pincer/objects/guild/member.py
pincer/utils/api_object.py
pincer/utils/conversion.py

Removing `_http` passing and getting it from the client

---

docs/CONTRIBUTING.md

-   `improvements`: gitmoji is now mandatory
We use it anyways for all commits (or at least we should). The prs that do not have it are squashed to have them.

:speech_balloon: Make gitmoji mandatory

---

pincer/objects/message/user_message.py

-   `fixed`: uses recursion to transform all APIObject objects into JSON serializable, because things like Embed are in list and were not set as json objects like mentionned in #305 :/

🐛 Transform `message.edit` list of APIObject to JSONSerializable

---

pincer/objects/__init__.py
pincer/objects/guild/__init__.py
pincer/objects/guild/invite.py

-   `adds`: `Invite.uses`, `Invite.max_uses`, `Invite.max_age`, `Invite.temporary`, `Invite.created_at`
-   `removed`: `InviteMetadata`

:sparkles: Moved InviteMetadata to Invite

---

pincer/commands/__init__.py
pincer/commands/commands.py
pincer/middleware/interaction_create.py
pincer/objects/app/command.py
pincer/utils/types.py

-   `adds`: Better logging. Please tell me if you are confused by the messages so I can make them better.
-   `fixed`: Commands are no longer removed every time the bot is loaded
-   `improvements`: Commands with the same name and different type and same name now work properly.

:bug: Fixed command registration and closes #256

---

setup_config/base.cfg

:arrow_up: Adding Python 3.10 as supported

---

pincer/objects/guild/channel.py

-   `fixed`:  __post_send_handler now deletes message instead of channel.
-   `fixed`:  __post_send and __post_send_handler type hints.
Currently http and delete_after aren't passed to UserMessage so this code never runs.
-   [ ] My Code follows the pep8 code style.

:bug: Fixes post_send_handler deleting channel instead of message

---

examples/cooldowns.py
pincer/objects/guild/channel.py
pincer/objects/guild/guild.py

- `adds`:
- New `Thread` class, which `PrivateThread` and `PublicThread` will inherit from.
- 8 methods to `Thread`:
- `start_with_message`
- `start`
- `join`
- `add_member`
- `leave`
- `remove_member`
- `get_member`
- `list_members`
- 4 methods to `Channel`:
- `list_active_threads`
- `list_public_archived_threads`
- `list_private_archived_threads`
- `list_joined_private_archived_threads`

:sparkles: Added 12 endpoints to `Channel`

---

pincer/utils/convert_message.py

-   `adds`: docstring on `convert_message`
-   `improvements`: a list of items can be used instead in the convert message function.
example usage:
```py
@command
async def help(ctx):
return Message(content="Help Command", attachements=[img_A, img_b], embed=[an_embed], component=[button1, button2]
@command
async def help(ctx):
return "Help Command", img_A, img_b, an_embed, button1, button2
```
Both methods work but the new one "converts" it into a message object with all the properties.

Message options

---

pincer/commands/commands.py
pincer/objects/message/user_message.py

The problem was that the event only sends parts of a UserMessage object. We either can do what I did or create a new object thats a clone of UserMessage but everything is optional.

:bug: Fix MessageUpdate event causing crash

---

pincer/core/http.py
pincer/objects/guild/channel.py
pincer/objects/guild/guild.py
pincer/objects/guild/webhook.py
pincer/objects/message/sticker.py
pincer/objects/message/user_message.py

-   `adds`: The ability to specify a `params` keyword argument in the HTTP get request, which will add the supplied dictionary to the query url, instead of doing it manually on each endpoint that requires this.
-   `fixed`: `Guild.search_guild_members` not working due to an incorrect variable in the request url.
-   `improvements`: All methods using query parameters were refactored for using this.

♻️ Added query params parameter to HTTP get requests

---

.github/workflows/sort_alls.yaml
pincer/__init__.py

Its kinda annoying how automatic sorting shows up after squashing/merging a PR so this should fix it
edit: I did not intend to make a branch on the main repo :skull: but im too lazy to fix it.

:bug: Make sort-alls work on all branches

---

pincer/core/dispatch.py
pincer/core/gateway.py

-   `fixed`: Disconnect bug where it started 5k times :skull: should be patched
Tested for ~5 hours at the time of making this PR and I forced a reconnect by unplugging my wifi xD to make sure it went smoothly.
Opcode 9 hasn't been tested since I haven't gotten the payload. Should work as it functions the same as the heartbeat disconnect.
Notes
close code 1001 was changed to 4000 because 1001 would turn the bot offline. 4000 is also a websocket close close officially available to application, discord uses it for unknown disconnects, and it isn't 1000.
`__should_reconnect` was renamed to `__should_resume` because that was what it actually did.
Line 325 was changed because I missed that in the docs when I read it the first time. …

:bug: gateway no longer starts multiple instances

---

pincer/client.py
pincer/objects/guild/guild.py

> before
```py
g = await self.get_guild(..., with_count=True)
member_count = g.approximate_member_count
await c.send(
Embed(description=f"There is {member_count} members in this server!")
)
```

✨ Adding approx member count

---

pincer/client.py
pincer/utils/event_mgr.py

```py
import asyncio
from pincer import Client
class Bot(Client):
@Client.event
async def on_ready(self):
print("Logged in as", self.bot)
await asyncio.sleep(5)
self.close()
if __name__ == "__main__":
b = Bot("...")
b.run()
```

✨ Adding `close`, `is_closed` and saving loop

---

.github/scripts/license_generator.py
.github/workflows/run_scripts.yml

It checks for every file (except `./pincer/__init__.py`) if the compressed license is present at the top of the file.

:construction_worker: Add a license generator

---

pincer/objects/guild/channel.py

```py
c = await self.get_channel(...)
async for m in c.history(limit=1000):
```

:sparkles: Adding message history

---

pincer/objects/guild/channel.py
pincer/objects/guild/guild.py
pincer/objects/message/user_message.py
pincer/utils/api_data.py

-   `adds`: a Custom class for Generator to be awaitable

♻️ Using a Custom class for Generator to be awaitable

---

examples/discord-welcomer/.env.example
examples/discord-welcomer/.gitignore
examples/discord-welcomer/README.md
examples/discord-welcomer/cogs/error_handler.py
examples/discord-welcomer/cogs/templates/welcome.html
examples/discord-welcomer/cogs/templates/welcome.variant.html
examples/discord-welcomer/cogs/welcome.py
examples/discord-welcomer/main.py
examples/discord-welcomer/requirements.txt
setup.cfg

A new example which shows how you would make a member welcomer, this example also shows a way on how you can import all cogs from a directory. 
Variant:
-   `adds`: A welcome example
-   [x] My code follows the pep8 code style.

:sparkles: Added an imager welcome example

---

pincer/objects/guild/channel.py

-   `adds`: Use a `TypeVar` for `Channel.from_id` as subclasses return their own type, not `Channel`.
-   `fixed`: fixes #413

:bug: use typevar for Channel.from_id return type

---

pincer/objects/guild/channel.py

-   `fixed`: fixes #414
-   `improvements`: Uses `utils.MessageConvertable` for `Channel.send`'s `message` param.

:bug: fix Channel.send `message` type
